markdown:               redcarpet
highlighter:            pygments

permalink:              /:year/:month/:title.html

name:                   Developers that rock
title:                  Developers that rock
url:                    http://developer.vtmer.com

authors:
    hbc:
        name: hbc
        github: bcho

    link:
        name: Link
        github: linkkingjay
